"""Family 7: Bio & Nano (acid green / toxic yellow / organic; splatter and swarm). Weapons 39-41.

Def schema (see docs/weapons/archetypes.md):
  id, name, family, tier, archetype, scope, zoom, dot, dps, ammo, heat, palette, shape,
  sound, params, hooks, vfx{six layers}, model, recipe, twist, hud, cooldown?, description?
"""

WEAPONS = [
    {
        "id": "acid_sprayer",
        "name": "Acid Sprayer",
        "description": "Pump-action green spray; corroded mobs drip and leave sizzling puddles.",
        "family": "bio", "tier": "common", "archetype": "cone", "dps": 8,
        "scope": "iron", "zoom": 1.0,
        "dot": {"style": "dot", "color": "#7cff3a", "range": 9},
        "ammo": {"type": "cell", "mag": 10}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "bio_acid", "core": "#eaffd0", "glow": "#7cff3a",
                    "trail": "#3a7a12", "accent": "#c8ff6a"},
        "shape": {"projectile": "droplet", "muzzle": "spray"},
        "sound": [["random.fizz", 0.6, 1.1, 0], ["block.lava.pop", 0.4, 1.5, 2]],
        "params": {"range": 8, "angle": 55, "dps": 8, "burst": True, "rate": 14,
                   "knockback": 0, "heat_rate": 1.0, "particle_size": 0.45, "muzzle_size": 0.5,
                   "corrode_ticks": 80, "pool_radius": 2, "pool_life": 80},
        "hooks": {"on_hit": [{"status": "weakness", "ticks": 80, "amp": 0},
                             {"status": "poison", "ticks": 80, "amp": 0},
                             {"field": "acid_pool", "radius": 2, "life": 80, "dps": 0,
                              "extra": {"status": [{"id": "weakness", "ticks": 80, "amp": 2},
                                                   {"id": "poison", "ticks": 80, "amp": 0}],
                                        "spawn": "gx:ember_trail"}},
                             {"vfx": "gx:orb_droplet", "size": 0.3, "life": 0.4, "count": 3}],
                  "on_tick": []},
        "vfx": {"idle": "gx:orb_droplet", "charge": "gx:swirl", "muzzle": "gx:orb_droplet",
                "body": "gx:orb_droplet", "impact": "gx:spark_burst", "screen": "vignette_toxic"},
        "model": {"form": "sprayer", "metal": "#4a5a3a"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:slime_ball", "minecraft:green_dye"]},
        "twist": "Every spray coats mobs in Corrode (Weakness + Poison-lite) and leaves a "
                 "lingering acid puddle that corrodes anything walking into it.",
        "custom": None,
    },
    {
        "id": "spore_launcher",
        "name": "Spore Launcher",
        "description": "Arcing spore pod bursts into a poison cloud and three homing darts.",
        "family": "bio", "tier": "rare", "archetype": "lob", "dps": 14,
        "scope": "dot", "zoom": 2.0,
        "dot": {"style": "dot", "color": "#d6ff3a", "range": 25},
        "ammo": {"type": "cell", "mag": 5}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "bio_spore", "core": "#f4ffd0", "glow": "#d6ff3a",
                    "trail": "#5a7a12", "accent": "#ffe86a"},
        "shape": {"projectile": "glob", "muzzle": "pod"},
        "sound": [["mob.ghast.shoot", 0.5, 1.2, 0], ["random.fizz", 0.4, 1.4, 6]],
        "params": {"speed": 16, "gravity": 0.05, "aoe": 3, "damage": 7, "fuse": 0,
                   "lifetime": 120, "count": 1, "spread": 0, "rate": 24, "size": 0.6,
                   "bounce": 0, "split": 3, "max_splits": 1, "split_homing": 8,
                   "split_speed": 22, "split_life": 60, "split_damage": 3, "split_size": 0.35,
                   "homing_turn": 0.3, "cloud_radius": 3, "cloud_life": 100, "cloud_dps": 2},
        "hooks": {"on_hit": [{"field": "spore_cloud", "radius": 3, "life": 100, "dps": 2,
                              "extra": {"status": [{"id": "poison", "ticks": 60, "amp": 0}],
                                        "spawn": "gx:orb_soft_orb"}},
                             {"vfx": "gx:orb_soft_orb", "size": 0.5, "life": 0.4, "count": 4}],
                  "on_tick": []},
        "vfx": {"idle": "gx:orb_soft_orb", "charge": "gx:swirl", "muzzle": "gx:orb_glob",
                "body": "gx:orb_glob", "impact": "gx:star_flash", "screen": "vignette_toxic"},
        "model": {"form": "launcher", "len": 13, "metal": "#5a6a3a"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:brown_mushroom", "minecraft:gunpowder"]},
        "twist": "The pod bursts into a 5 s poison cloud and throws three homing spore darts "
                 "that chase nearby mobs.",
        "custom": "spore_launcher",
    },
    {
        "id": "nanite_swarm_rifle",
        "name": "Nanite Swarm Rifle",
        "description": "A flocking nanite cloud that re-seeks up to three targets before dissolving.",
        "family": "bio", "tier": "epic", "archetype": "bolt", "dps": 22,
        "scope": "lock", "zoom": 2.0,
        "dot": {"style": "dot", "color": "#c8d8e0", "range": 30},
        "ammo": {"type": "cell", "mag": 20}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "bio_nanite", "core": "#f2ffff", "glow": "#7fd8c8",
                    "trail": "#2a7a72", "accent": "#c8e8e0"},
        "shape": {"projectile": "plume", "muzzle": "hive"},
        "sound": [["random.fizz", 0.3, 1.9, 0], ["note.pling", 0.3, 2.0, 1]],
        "params": {"speed": 30, "gravity": 0, "homing": 30, "homing_turn": 0.35,
                   "lifetime": 90, "rate": 6, "damage": 6, "count": 1, "spread": 0,
                   "size": 0.45, "muzzle_size": 0.4, "pierce": 3, "aoe": 0, "bounce": 0,
                   "max_retargets": 3, "retarget_range": 8, "flock": 0.35},
        "hooks": {"on_hit": [{"status": "poison", "ticks": 60, "amp": 1},
                             {"vfx": "gx:spark_burst", "size": 0.3, "life": 0.3, "count": 4}],
                  "on_tick": []},
        "vfx": {"idle": "gx:snow_mote", "charge": "gx:static_arc", "muzzle": "gx:orb_plume",
                "body": "gx:orb_plume", "impact": "gx:spark_burst", "screen": "scope_lock"},
        "model": {"form": "rifle", "len": 20, "thick": 3, "tall": 3, "scope": True,
                  "drum": True, "metal": "#c8d0d8"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:honeycomb", "minecraft:copper_ingot"]},
        "twist": "The nanite cloud flocks toward the nearest mob, re-seeks the next one after "
                 "each kill, and dissolves after three targets.",
        "custom": "nanite_swarm_rifle",
    },
]
