"""Family 9: Cosmic & Mythic (layered gold / white / rainbow palettes). Weapons 46-50.

Def schema (see docs/weapons/archetypes.md):
  id, name, family, tier, archetype, scope, zoom, dot, dps, ammo, heat, palette, shape,
  sound, params, hooks, vfx{six layers}, model, recipe, twist, hud, cooldown?, description?
"""

WEAPONS = [
    {
        "id": "aurora_lance",
        "name": "Aurora Lance",
        "description": "Rainbow beam that cycles fire, ice, shock and toxic every second.",
        "family": "cosmic", "tier": "mythic", "archetype": "beam", "dps": 30,
        "scope": "focus", "zoom": 4.0,
        "dot": {"style": "dot", "color": "#ffd45a", "range": 40},
        "ammo": {"type": "heat"}, "heat": {"max": 100, "per_shot": 0, "cool": 18},
        "hud": {"kind": "heat"},
        "palette": {"name": "cosmic_aurora", "core": "#ffffff", "glow": "#ffd45a",
                    "trail": "#6a3ad8", "accent": "#7cff9a"},
        "shape": {"projectile": "bar", "muzzle": "ribbon"},
        "sound": [["beacon.activate", 0.7, 1.4, 0], ["random.fizz", 0.3, 1.9, 2]],
        "params": {"range": 40, "dps": 30, "width": 0.34, "heat_rate": 1.4, "tick_rate": 4,
                   "refract": True, "refract_glass": True, "element_ticks": 20,
                   "status_ticks": 60, "combo_mult": 1.3, "arc_radius": 6},
        "hooks": {"on_hit": [{"vfx": "gx:ring_wave", "size": 0.5, "life": 0.25}], "on_tick": []},
        "vfx": {"idle": "gx:swirl", "charge": "gx:field_glow", "muzzle": "gx:beam_bar",
                "body": "gx:beam_bar", "impact": "gx:ring_wave", "screen": "ring_big"},
        "model": {"form": "lance", "len": 30, "rings": 3, "metal": "#5a4a7a"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:gold_ingot",
                                   "minecraft:amethyst_shard", "minecraft:diamond"]},
        "twist": "Every second the beam cycles fire -> ice -> shock -> toxic, recolouring the "
                 "beam and applying that element's status; fire into ice shatters and ice "
                 "into shock arcs to nearby mobs.",
        "custom": "aurora_lance",
    },
    {
        "id": "supernova_rifle",
        "name": "Supernova Rifle",
        "description": "3 s overcharge fires a white slug that detonates as a supernova.",
        "family": "cosmic", "tier": "ultimate", "archetype": "charge", "dps": 30,
        "cooldown": 60,
        "scope": "scope4", "zoom": 4.0,
        "dot": {"style": "dot_ring", "color": "#fff2c0", "range": 96},
        "ammo": {"type": "cell", "mag": 1}, "heat": None, "hud": {"kind": "charge"},
        "palette": {"name": "cosmic_supernova", "core": "#ffffff", "glow": "#ffd45a",
                    "trail": "#ff5a2b", "accent": "#5a9aff"},
        "shape": {"projectile": "star", "muzzle": "lattice"},
        "sound": [["random.explode", 1.0, 0.8, 0], ["mob.ghast.shoot", 0.8, 0.6, 2],
                  ["ambient.cave", 0.55, 0.45, 40]],
        "params": {"mode": "bolt", "charge_ticks": 60, "hold_ticks": 60, "min_ticks": 20,
                   "speed": 40, "gravity": 0, "lifetime": 44, "damage": 30, "count": 1,
                   "size": 1.0, "muzzle_size": 1.2, "aoe": 10, "aoe_mult": 1.0,
                   "field_radius": 10, "field_life": 60, "field_dps": 6, "field_push": 0.9,
                   "collapse_dmg": 20, "collapse_knock": 1.6,
                   "grief": {"radius": 4, "from": ["minecraft:sand", "minecraft:dirt",
                   "minecraft:gravel", "minecraft:grass_block"], "to": "minecraft:blackstone",
                   "cap": 30},
                   "tiers": [{"ticks": 20, "damage": 22, "speed": 45, "size": 0.7, "aoe": 4,
                              "lifetime": 30},
                             {"ticks": 40, "damage": 40, "speed": 40, "size": 0.9, "aoe": 7,
                              "lifetime": 36},
                             {"ticks": 60, "damage": 70, "speed": 34, "size": 1.2, "aoe": 10,
                              "lifetime": 44, "cooldown": 60}]},
        "hooks": {"on_hit": [{"vfx": "gx:star_flash", "size": 0.6, "life": 0.25}], "on_tick": []},
        "vfx": {"idle": "gx:orb_star", "charge": "gx:swirl", "muzzle": "gx:star_flash",
                "body": "gx:orb_star", "impact": "gx:ring_wave", "screen": "vignette_whiteout"},
        "model": {"form": "rifle", "len": 24, "thick": 4, "tall": 4, "scope": True,
                  "scope_len": 10, "fins": True, "metal": "#6a5a8a"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:netherite_ingot",
                                   "minecraft:gold_block", "minecraft:glowstone"]},
        "twist": "A 3 s overcharge fires a white slug that detonates as a supernova (radius "
                 "10, distance falloff, outward knockback, collapsing field) on a 60 s "
                 "cooldown, with a white screen flash and 2 s of sound ducking.",
        "custom": "supernova_rifle",
    },
    {
        "id": "starforge_bow",
        "name": "Starforge Bow-Gun",
        "description": "Star arrows stick as constellation nodes; three link into a field.",
        "family": "cosmic", "tier": "mythic", "archetype": "bolt", "dps": 30,
        "scope": "scope4", "zoom": 4.0,
        "dot": {"style": "dot", "color": "#ffd45a", "range": 64},
        "ammo": {"type": "cell", "mag": 6}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "cosmic_starforge", "core": "#fff6d0", "glow": "#ffd45a",
                    "trail": "#8a6a2a", "accent": "#ffffff"},
        "shape": {"projectile": "star", "muzzle": "bow_limb"},
        "sound": [["crossbow.shoot", 0.8, 1.1, 0], ["beacon.activate", 0.4, 1.8, 1]],
        "params": {"speed": 55, "gravity": 0.015, "lifetime": 160, "rate": 20, "damage": 30,
                   "count": 1, "spread": 0, "size": 0.45, "muzzle_size": 0.6, "stick": True,
                   "node_life": 160, "node_max": 5, "node_link": 24, "field_dps": 10,
                   "field_radius": 4, "field_life": 80},
        "hooks": {"on_hit": [{"vfx": "gx:star_flash", "size": 0.5, "life": 0.25}], "on_tick": []},
        "vfx": {"idle": "gx:swirl", "charge": "gx:star_flash", "muzzle": "gx:star_flash",
                "body": "gx:orb_star", "impact": "gx:crystal_burst", "screen": "star"},
        "model": {"form": "bow", "metal": "#6b5a3a"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:gold_ingot",
                                   "minecraft:string", "minecraft:diamond"]},
        "twist": "Arrows stick where they land as constellation nodes (8 s); 3 or more nodes "
                 "draw luminous lines and form a star field dealing 10 dps to mobs inside, "
                 "recycling the oldest past five.",
        "custom": "starforge_bow",
    },
    {
        "id": "chrono_pistol",
        "name": "Chrono Pistol",
        "description": "Tags a target for 3 s; sneak-fire rewinds it along its recorded path.",
        "family": "cosmic", "tier": "mythic", "archetype": "hitscan", "dps": 30,
        "scope": "dot", "zoom": 2.0,
        "dot": {"style": "dot_cross", "color": "#4affd8", "range": 40},
        "ammo": {"type": "cell", "mag": 12}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "cosmic_chrono", "core": "#eaffff", "glow": "#4affd8",
                    "trail": "#1a7a6a", "accent": "#ffd45a"},
        "shape": {"projectile": "hex", "muzzle": "gear"},
        "sound": [["random.orb", 0.6, 1.5, 0], ["note.pling", 0.5, 0.8, 0],
                  ["beacon.activate", 0.4, 1.9, 2]],
        "params": {"range": 40, "damage": 12, "rate": 8, "pierce": 1, "tracer_size": 0.24,
                   "muzzle_size": 0.5, "rewind_ticks": 60, "rewind_dmg_per_block": 3,
                   "rewind_dmg_max": 30, "rewind_cooldown": 30, "trail_max": 60},
        "hooks": {"on_hit": [{"vfx": "gx:star_flash", "size": 0.4, "life": 0.2}], "on_tick": []},
        "vfx": {"idle": "gx:swirl", "charge": "gx:ring_wave", "muzzle": "gx:star_flash",
                "body": "gx:beam_needle", "impact": "gx:ring_wave", "screen": "hourglass"},
        "model": {"form": "pistol", "tall": 4, "metal": "#7a6a4a"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:gold_ingot",
                                   "minecraft:clock", "minecraft:amethyst_shard"]},
        "twist": "A hit tags the target for 3 s, recording its position every tick; sneak-fire "
                 "rewinds it to where it stood, dealing damage proportional to the distance "
                 "travelled (a failed teleport still lands the damage and the streak).",
        "custom": "chrono_pistol",
    },
    {
        "id": "good_boy_cannon",
        "name": "Good Boy Cannon",
        "description": "Paw-print star bolts; heals and buffs your pup, sneak-fire calls them.",
        "family": "cosmic", "tier": "mythic", "archetype": "bolt", "dps": 30,
        "scope": "dot", "zoom": 2.0,
        "dot": {"style": "dot", "color": "#ffd7ea", "range": 40},
        "ammo": {"type": "cell", "mag": 8}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "cosmic_goodboy", "core": "#ffffff", "glow": "#ffd7ea",
                    "trail": "#ff9ec4", "accent": "#ffe9a0"},
        "shape": {"projectile": "paw", "muzzle": "paw_muzzle"},
        "sound": [["mob.wolf.bark", 0.7, 1.4, 0], ["random.orb", 0.5, 1.9, 2],
                  ["mob.wolf.ambient", 0.4, 1.6, 6]],
        "params": {"speed": 50, "gravity": 0.01, "homing": 6, "homing_turn": 0.3,
                   "lifetime": 50, "rate": 10, "damage": 15, "count": 1, "spread": 0,
                   "size": 0.5, "muzzle_size": 0.6, "aoe": 2.0, "aoe_mult": 0.6,
                   "heal": 8, "buff_ticks": 200, "call_radius": 30, "dash_offset": 0.6},
        "hooks": {"on_hit": [{"vfx": "gx:orb_paw", "size": 0.5, "life": 0.3, "count": 2}],
                  "on_tick": []},
        "vfx": {"idle": "gx:orb_paw", "charge": "gx:orb_paw", "muzzle": "gx:orb_paw",
                "body": "gx:orb_star", "impact": "gx:star_flash", "screen": "marker_heart"},
        "model": {"form": "cannon", "len": 12, "metal": "#8a6a7a"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:gold_ingot",
                                   "minecraft:bone", "minecraft:pink_dye"]},
        "twist": "Paw bolts heal a tamed galaxy:pup and grant Speed + Strength for 10 s; "
                 "sneak-fire launches a bone starburst that teleport-dashes every tamed pup "
                 "within 30 blocks to your side.",
        "custom": "good_boy_cannon",
    },
]
