"""Family 4: Cryo (white / ice-blue; shards, mist, frost). Weapons 23-26.

Def schema (see docs/weapons/archetypes.md):
  id, name, family, tier, archetype, scope, zoom, dot, dps, ammo, heat, palette, shape,
  sound, params, hooks, vfx{six layers}, model, recipe, twist, hud, cooldown?, description?
"""

WEAPONS = [
    {
        "id": "frost_lance",
        "name": "Frost Lance",
        "description": "Ice-blue beam that stacks Chill; five stacks freeze the target solid.",
        "family": "cryo", "tier": "rare", "archetype": "beam", "dps": 14,
        "scope": "dot", "zoom": 2.0,
        "dot": {"style": "dot", "color": "#bfe6ff", "range": 24},
        "ammo": {"type": "heat"}, "heat": {"max": 100, "per_shot": 0, "cool": 8},
        "hud": {"kind": "heat"},
        "palette": {"name": "cryo_lance", "core": "#ffffff", "glow": "#8fd8ff",
                    "trail": "#2a6a9a", "accent": "#d6f2ff"},
        "shape": {"projectile": "needle", "muzzle": "frost_ring"},
        "sound": [["random.glass", 0.5, 1.6, 0], ["beacon.activate", 0.4, 1.8, 0]],
        "params": {"range": 20, "dps": 14, "width": 0.28, "heat_rate": 1.0, "tick_rate": 4,
                   "chill_max": 5, "freeze_ticks": 60},
        "hooks": {"on_hit": [{"vfx": "gx:snow_mote", "size": 0.3, "life": 0.3, "count": 2}],
                  "on_tick": []},
        "vfx": {"idle": "gx:snow_mote", "charge": "gx:crystal_burst", "muzzle": "gx:orb_needle",
                "body": "gx:beam_needle", "impact": "gx:crystal_burst", "screen": "vignette_frost"},
        "model": {"form": "lance", "len": 30, "rings": 3, "metal": "#a8c8dd"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:blue_ice", "minecraft:amethyst_shard"]},
        "twist": "The beam stacks Chill once per second of contact; at five stacks the "
                 "target freezes solid (Slowness 255 for 3 s) and shatters in a crystal burst.",
        "custom": "frost_lance",
    },
    {
        "id": "glacier_shard_launcher",
        "name": "Glacier Shard Launcher",
        "description": "Jagged ice shards stick fast and grow a slowing crystal cluster.",
        "family": "cryo", "tier": "rare", "archetype": "bolt", "dps": 14,
        "scope": "iron", "zoom": 1.0,
        "dot": {"style": "dot", "color": "#9fe0ff", "range": 48},
        "ammo": {"type": "cell", "mag": 6}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "cryo_shard", "core": "#ffffff", "glow": "#7fd0ff",
                    "trail": "#1f5c88", "accent": "#c8ecff"},
        "shape": {"projectile": "shard", "muzzle": "crystal"},
        "sound": [["crossbow.shoot", 0.7, 1.1, 0], ["block.glass.break", 0.4, 1.6, 2]],
        "params": {"speed": 35, "gravity": 0.02, "lifetime": 60, "rate": 20, "damage": 14,
                   "count": 1, "size": 0.6, "muzzle_size": 0.6, "stick": True, "fuse": 30,
                   "aoe": 2.5, "aoe_mult": 0.5, "cluster_radius": 3, "cluster_life": 120},
        "hooks": {"on_hit": [{"vfx": "gx:crystal_burst", "size": 0.5, "life": 0.4, "count": 3}],
                  "on_tick": []},
        "vfx": {"idle": "gx:snow_mote", "charge": "gx:crystal_burst", "muzzle": "gx:orb_shard",
                "body": "gx:orb_shard", "impact": "gx:crystal_burst", "screen": "vignette_whiteout"},
        "model": {"form": "rifle", "len": 20, "thick": 3, "tall": 3, "scope": True,
                  "fins": True, "metal": "#8fb8d0"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:packed_ice", "minecraft:prismarine_shard"]},
        "twist": "Shards stick into whatever they hit, then fuse into a 3-spike crystal "
                 "cluster that slows every mob within 3 blocks for 6 s.",
        "custom": "glacier_shard_launcher",
    },
    {
        "id": "blizzard_cannon",
        "name": "Blizzard Cannon",
        "description": "Channelled cone of wind and snow that widens the longer you fire.",
        "family": "cryo", "tier": "epic", "archetype": "cone", "dps": 22,
        "scope": "iron", "zoom": 1.0,
        "dot": {"style": "dot", "color": "#dff4ff", "range": 16},
        "ammo": {"type": "heat"}, "heat": {"max": 100, "per_shot": 0, "cool": 10},
        "hud": {"kind": "heat"},
        "palette": {"name": "cryo_blizzard", "core": "#ffffff", "glow": "#a8e0ff",
                    "trail": "#3a7aa8", "accent": "#e0f6ff"},
        "shape": {"projectile": "plume", "muzzle": "turbine"},
        "sound": [["block.powder_snow.break", 0.6, 1.2, 0], ["random.fizz", 0.3, 1.4, 1]],
        "params": {"range": 12, "angle": 90, "dps": 22, "knockback": 0, "rate": 6,
                   "heat_rate": 0.9, "particle_size": 0.7, "muzzle_size": 0.8,
                   "max_angle": 140, "widen_step": 0.7, "knock": 0.45},
        "hooks": {"on_hit": [{"status": "slowness", "ticks": 40, "amp": 0}], "on_tick": []},
        "vfx": {"idle": "gx:snow_mote", "charge": "gx:swirl", "muzzle": "gx:orb_plume",
                "body": "gx:orb_plume", "impact": "gx:ring_wave", "screen": "vignette_frost"},
        "model": {"form": "cannon", "len": 16, "metal": "#7fa0b8"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:snowball", "minecraft:blue_ice"]},
        "twist": "The longer you channel, the wider the cone: a whiteout frosts the screen "
                 "edges, a snowdrift piles up, and mobs are pushed further and further away.",
        "custom": "blizzard_cannon",
    },
    {
        "id": "absolute_zero_sniper",
        "name": "Absolute Zero Sniper",
        "description": "Bolt-action thermal sniper; a hit traps mobs in a stasis bubble.",
        "family": "cryo", "tier": "mythic", "archetype": "hitscan", "dps": 30,
        "scope": "thermal", "zoom": 8.0,
        "dot": {"style": "dot", "color": "#bfe6ff", "range": 100},
        "ammo": {"type": "cell", "mag": 4}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "cryo_zero", "core": "#ffffff", "glow": "#bfe6ff",
                    "trail": "#4a7fa8", "accent": "#eaf7ff"},
        "shape": {"projectile": "star", "muzzle": "frost_scope"},
        "sound": [["crossbow.shoot", 0.9, 0.9, 0], ["random.glass", 0.6, 0.7, 2]],
        "params": {"range": 100, "damage": 20, "rate": 14, "pierce": 1,
                   "tracer_size": 0.16, "muzzle_size": 0.55, "shatter_mult": 0.5},
        "hooks": {"on_hit": [{"field": "stasis", "radius": 3, "life": 60,
                              "extra": {"status": [{"id": "slowness", "ticks": 60, "amp": 255}],
                                        "collapse": {"dmg": 10, "knock": 1.0}}}],
                  "on_tick": []},
        "vfx": {"idle": "gx:snow_mote", "charge": "gx:field_glow", "muzzle": "gx:star_flash",
                "body": "gx:beam_needle", "impact": "gx:shock_disc", "screen": "thermal_tint"},
        "model": {"form": "sniper", "len": 34, "metal": "#c9d6e2"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:diamond", "minecraft:blue_ice"]},
        "twist": "A hit seals mobs in a stasis bubble; hitting any mob inside shatters it "
                 "early for bonus damage scaled by how many mobs are trapped.",
        "custom": "absolute_zero_sniper",
    },
]
