"""Family 3: Fire (orange/yellow/blue flame, volume and drama). Weapons 17-22.

Def schema (see docs/weapons/archetypes.md):
  id, name, family, tier, archetype, scope, zoom, dot, dps, ammo, heat, palette, shape,
  sound, params, hooks, vfx{six layers}, model, recipe, twist, hud, cooldown?, description?
"""

WEAPONS = [
    {
        "id": "dragon_breath_flamer",
        "name": "Dragon-Breath Flamer",
        "description": "Continuous flame cone; the colour ramps orange to blue for bonus damage.",
        "family": "fire", "tier": "rare", "archetype": "cone", "dps": 14,
        "scope": "iron", "zoom": 1.0,
        "dot": {"style": "dot", "color": "#ff6a1a", "range": 9},
        "ammo": {"type": "heat"}, "heat": {"max": 100, "per_shot": 1.2, "cool": 3},
        "hud": {"kind": "fuel"},
        "palette": {"name": "fire_dragon", "core": "#fffbe8", "glow": "#ff6a1a",
                    "trail": "#7a2a06", "accent": "#ffc46a"},
        "shape": {"projectile": "plume", "muzzle": "billow"},
        "sound": [["mob.blaze.burn", 0.5, 1.3, 0], ["fire.ignite", 0.3, 1.6, 2]],
        "params": {"range": 9, "angle": 60, "dps": 14, "knockback": 0, "rate": 10,
                   "heat_rate": 1.2, "particle_size": 0.7, "muzzle_size": 0.7,
                   "ramp_ticks": 80, "ignite": 5,
                   "grief": {"radius": 2, "from": ["minecraft:oak_leaves", "minecraft:birch_leaves",
                             "minecraft:spruce_leaves", "minecraft:jungle_leaves",
                             "minecraft:acacia_leaves", "minecraft:dark_oak_leaves",
                             "minecraft:mangrove_leaves", "minecraft:short_grass",
                             "minecraft:tall_grass"], "to": "minecraft:fire", "cap": 4}},
        "hooks": {"on_hit": [{"vfx": "gx:ember_trail", "size": 0.5, "life": 0.4, "count": 3}],
                  "on_tick": []},
        "vfx": {"idle": "gx:ember_trail", "charge": "gx:smoke_trail", "muzzle": "gx:orb_plume",
                "body": "gx:orb_plume", "impact": "gx:spark_burst", "screen": "vignette_heat"},
        "model": {"form": "cannon", "len": 14, "metal": "#6a3a1a"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:blaze_rod", "minecraft:gunpowder"]},
        "twist": "Continuous fire ramps the flame orange to yellow to blue over 4 s, and at "
                 "blue the cone deals x1.5 damage while the tank gauge drains.",
        "custom": "dragon_breath_flamer",
    },
    {
        "id": "fireball_launcher",
        "name": "Fireball Launcher",
        "description": "Slow lumpy fireball; leaves a burning trail and bounces once.",
        "family": "fire", "tier": "common", "archetype": "lob", "dps": 8,
        "scope": "dot", "zoom": 2.0,
        "dot": {"style": "dot", "color": "#ff8a1a", "range": 48},
        "ammo": {"type": "cell", "mag": 8}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "fire_ember", "core": "#fff2c8", "glow": "#ff8a1a",
                    "trail": "#7a3308", "accent": "#ffb060"},
        "shape": {"projectile": "glob", "muzzle": "flared"},
        "sound": [["mob.ghast.shoot", 0.6, 0.8, 0], ["item.firecharge.use", 0.5, 1.0, 0]],
        "params": {"speed": 14, "gravity": 0.05, "aoe": 3, "damage": 8, "fuse": 0,
                   "lifetime": 120, "count": 1, "spread": 0, "rate": 20, "size": 0.7,
                   "bounce": 1, "alt_count": 3, "alt_spread": 12, "ignite": 5},
        "hooks": {"on_hit": [{"field": "ember_trail", "radius": 2, "life": 20, "dps": 2,
                              "extra": {"spawn": "gx:ember_trail"}}],
                  "on_tick": []},
        "vfx": {"idle": "gx:ember_trail", "charge": "gx:smoke_trail", "muzzle": "gx:orb_glob",
                "body": "gx:orb_glob", "impact": "gx:ring_wave", "screen": "vignette_heat"},
        "model": {"form": "launcher", "len": 14, "metal": "#6a4a2a"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:gunpowder", "minecraft:blaze_powder"]},
        "twist": "Fireballs leave a 1 s burning trail that scorches anything crossing it and "
                 "bounce once off the floor, while sneak-fire throws a triple spread.",
        "custom": "fireball_launcher",
    },
    {
        "id": "meteor_rifle",
        "name": "Meteor Caller Rifle",
        "description": "Marker beam calls five meteors down onto the marked spot.",
        "family": "fire", "tier": "epic", "archetype": "hitscan", "dps": 22,
        "scope": "scope4", "zoom": 4.0,
        "dot": {"style": "dot_ring", "color": "#ff5a12", "range": 90},
        "ammo": {"type": "heat"}, "heat": None, "hud": {"kind": "charges"},
        "palette": {"name": "fire_meteor", "core": "#fff0c0", "glow": "#ff5a12",
                    "trail": "#7a1f04", "accent": "#ff9a3a"},
        "shape": {"projectile": "shard", "muzzle": "drum"},
        "sound": [["beacon.activate", 0.7, 0.9, 0], ["random.explode", 0.8, 0.7, 20]],
        "params": {"range": 90, "damage": 4, "rate": 40, "pierce": 0, "tracer_size": 0.28,
                   "muzzle_size": 0.7, "charges": 3, "refill_ticks": 240, "marker_delay": 20,
                   "meteor_count": 5, "meteor_gap": 15, "meteor_spread": 6, "meteor_aoe": 4,
                   "meteor_damage": 12, "inbound_ticks": 20},
        "hooks": {"on_hit": [{"field": "meteor_scar", "radius": 3, "life": 60, "dps": 2,
                              "extra": {"spawn": "gx:ember_trail"}}],
                  "on_tick": []},
        "vfx": {"idle": "gx:ember_trail", "charge": "gx:swirl", "muzzle": "gx:star_flash",
                "body": "gx:orb_shard", "impact": "gx:debris_burst", "screen": "hourglass"},
        "model": {"form": "rifle", "len": 22, "thick": 4, "tall": 4, "scope": True,
                  "drum": True, "metal": "#5a3a2a"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:blaze_rod", "minecraft:gunpowder"]},
        "twist": "Three meteor charges refill one every 12 s, and each shot paints a marker "
                 "beam that 1 s later brings five meteors down over 3 s, each a 4-block crater.",
        "custom": "meteor_rifle",
    },
    {
        "id": "phoenix_repeater",
        "name": "Phoenix Repeater",
        "description": "Flaming phoenix bolt flies out and returns; catch it to heal.",
        "family": "fire", "tier": "mythic", "archetype": "bolt", "dps": 30,
        "scope": "dot", "zoom": 2.0,
        "dot": {"style": "dot", "color": "#ffb02b", "range": 64},
        "ammo": {"type": "cell", "mag": 8}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "fire_phoenix", "core": "#fffce0", "glow": "#ffae2a",
                    "trail": "#8a4a08", "accent": "#ffe0a0"},
        "shape": {"projectile": "plume", "muzzle": "crest"},
        "sound": [["item.trident.throw", 0.7, 1.2, 0], ["mob.blaze.shoot", 0.5, 1.4, 0]],
        "params": {"speed": 40, "gravity": 0, "homing": 8, "homing_turn": 0.35, "lifetime": 90,
                   "rate": 10, "damage": 14, "count": 1, "spread": 0, "size": 0.55,
                   "muzzle_size": 0.6, "pierce": 1, "turn_at": 35, "catch_radius": 2,
                   "heal": 4},
        "hooks": {"on_hit": [{"vfx": "gx:ember_trail", "size": 0.6, "life": 0.4, "count": 4}],
                  "on_tick": []},
        "vfx": {"idle": "gx:ember_trail", "charge": "gx:swirl", "muzzle": "gx:orb_plume",
                "body": "gx:beam_plume", "impact": "gx:star_flash", "screen": "marker_heart"},
        "model": {"form": "rifle", "len": 18, "thick": 3, "tall": 3, "fins": True,
                  "metal": "#7a5a2a"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:gold_ingot",
                                   "minecraft:blaze_rod", "minecraft:feather"]},
        "twist": "The phoenix flies out 35 blocks then curves back to the shooter, and "
                 "catching it within 2 blocks heals 2 hearts and refunds the shot.",
        "custom": "phoenix_repeater",
    },
    {
        "id": "magma_mortar",
        "name": "Magma Mortar",
        "description": "High-arc lava blobs leave merging magma pools that melt armour.",
        "family": "fire", "tier": "epic", "archetype": "lob", "dps": 22,
        "scope": "rangefinder", "zoom": 4.0,
        "dot": {"style": "dot", "color": "#ff4a10", "range": 64},
        "ammo": {"type": "cell", "mag": 6}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "fire_magma", "core": "#fff0d0", "glow": "#ff4a10",
                    "trail": "#6a1a04", "accent": "#ff8a4a"},
        "shape": {"projectile": "glob", "muzzle": "mouth"},
        "sound": [["mob.magmacube.big", 0.6, 1.0, 0], ["block.lava.pop", 0.4, 1.2, 4]],
        "params": {"speed": 12, "gravity": 0.35, "aoe": 4, "damage": 14, "fuse": 0,
                   "lifetime": 140, "count": 1, "spread": 0, "rate": 40, "size": 0.7,
                   "merge_radius": 3, "pool_radius": 3, "pool_life": 100, "pool_dps": 4,
                   "pool_grow": 1, "pool_max_radius": 6, "pool_extend": 80,
                   "pool_max_life": 240},
        "hooks": {"on_hit": [{"field": "magma_pool", "radius": 3, "life": 100, "dps": 4,
                              "extra": {"status": [{"id": "weakness", "ticks": 40, "amp": 0}],
                                        "spawn": "gx:ember_trail"}}],
                  "on_tick": []},
        "vfx": {"idle": "gx:field_glow", "charge": "gx:smoke_trail", "muzzle": "gx:orb_glob",
                "body": "gx:orb_glob", "impact": "gx:ring_wave", "screen": "arrow_down"},
        "model": {"form": "mortar", "metal": "#5a2a1a"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:magma_block", "minecraft:gunpowder"]},
        "twist": "Blobs landing within 3 blocks of an existing pool grow it (+1 radius, "
                 "+4 s) instead of stacking a second one, and mobs in a pool get Molten.",
        "custom": "magma_mortar",
    },
    {
        "id": "inferno_revolver",
        "name": "Inferno Revolver",
        "description": "Six-shot fire revolver; fan the hammer or beat the speedloader QTE.",
        "family": "fire", "tier": "rare", "archetype": "hitscan", "dps": 14,
        "scope": "iron", "zoom": 1.0,
        "dot": {"style": "dot", "color": "#ff5a20", "range": 32},
        "ammo": {"type": "cell", "mag": 6}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "fire_inferno", "core": "#fff4e0", "glow": "#ff5a20",
                    "trail": "#7a2408", "accent": "#ffb07a"},
        "shape": {"projectile": "dart", "muzzle": "cylinder"},
        "sound": [["item.firecharge.use", 0.7, 0.9, 0], ["random.fizz", 0.4, 1.4, 6]],
        "params": {"range": 32, "damage": 15, "rate": 20, "pierce": 0, "tracer_size": 0.22,
                   "muzzle_size": 0.6, "reload_ticks": 40, "fan_ticks": 16, "fan_spread": 14,
                   "qte_from": 32, "ignite": 5, "boom_damage": 10, "boom_aoe": 3},
        "hooks": {"on_hit": [{"vfx": "gx:spark_burst", "size": 0.4, "life": 0.3, "count": 4}],
                  "on_tick": []},
        "vfx": {"idle": "gx:ember_trail", "charge": "gx:spark_burst", "muzzle": "gx:muzzle_flash",
                "body": "gx:orb_dart", "impact": "gx:spark_burst", "screen": "vignette_heat"},
        "model": {"form": "revolver", "metal": "#5a3a2a"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:blaze_powder", "minecraft:gunpowder"]},
        "twist": "Sneak-fire fans the hammer to empty the cylinder in 0.8 s with wide spread, "
                 "and a speedloader press in the green window loads an explosive round.",
        "custom": "inferno_revolver",
    },
]
