"""Family 2: Laser (thin, hard-edged, saturated reds/oranges/greens/whites; long beams,
mirrors). Weapons 09-16.

Def schema (see docs/weapons/archetypes.md):
  id, name, family, tier, archetype, scope, zoom, dot, dps, ammo, heat, palette, shape,
  sound, params, hooks, vfx{six layers}, model, recipe, twist, hud, cooldown?, description?
"""

WEAPONS = [
    {
        "id": "red_dot_marksman",
        "name": "Red Dot Marksman",
        "description": "Semi-auto crimson hairline; always-on dot, headshot bonus.",
        "family": "laser", "tier": "common", "archetype": "hitscan", "dps": 8,
        "scope": "dot", "zoom": 3.0,
        "dot": {"style": "dot", "color": "#ff2a2a", "range": 80, "always": True},
        "ammo": {"type": "cell", "mag": 8}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "laser_crimson", "core": "#fff0f0", "glow": "#ff2a2a",
                    "trail": "#8a1010", "accent": "#ff8a7a"},
        "shape": {"projectile": "dart", "muzzle": "point"},
        "sound": [["crossbow.shoot", 0.7, 1.7, 0], ["random.fizz", 0.2, 2.0, 1]],
        "params": {"range": 80, "damage": 8, "rate": 20, "pierce": 0, "headshot_mult": 1.8,
                   "tracer_size": 0.08, "muzzle_size": 0.3},
        "hooks": {"on_hit": [{"vfx": "gx:star_flash", "size": 0.25, "life": 0.15}], "on_tick": []},
        "vfx": {"idle": "gx:ember_trail", "charge": "gx:dot_dot", "muzzle": "gx:muzzle_flash",
                "body": "gx:beam_needle", "impact": "gx:star_flash", "screen": "vignette_heat"},
        "model": {"form": "rifle", "len": 22, "thick": 3, "tall": 3, "scope": True,
                  "scope_len": 4, "metal": "#4a3f3f"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:redstone", "minecraft:glass"]},
        "twist": "The crimson dot is always on and visible to everyone, so aiming is a "
                 "tell; a hit on the top 15% of a target deals x1.8.",
        "custom": None,
    },
    {
        "id": "prism_beam",
        "name": "Prism Beam",
        "description": "White channel beam that refracts into R/G/B spectra through glass.",
        "family": "laser", "tier": "epic", "archetype": "beam", "dps": 22,
        "scope": "focus", "zoom": 4.0,
        "dot": {"style": "dot", "color": "#ffffff", "range": 48},
        "ammo": {"type": "heat"}, "heat": {"max": 100, "per_shot": 0, "cool": 10},
        "hud": {"kind": "heat"},
        "palette": {"name": "laser_prism", "core": "#ffffff", "glow": "#ff5a5a",
                    "trail": "#3a7aff", "accent": "#5aff8a"},
        "shape": {"projectile": "bar", "muzzle": "prism"},
        "sound": [["beacon.activate", 0.6, 1.3, 0], ["random.fizz", 0.3, 1.8, 0]],
        "params": {"range": 30, "dps": 14, "width": 0.22, "heat_rate": 1.2, "tick_rate": 4,
                   "refract": True, "refract_glass": True},
        "hooks": {"on_hit": [{"status": "slowness", "ticks": 20, "amp": 0},
                             {"vfx": "gx:star_flash", "size": 0.35, "life": 0.2}],
                  "on_tick": []},
        "vfx": {"idle": "gx:swirl", "charge": "gx:crystal_burst", "muzzle": "gx:crystal_burst",
                "body": "gx:beam_bar", "impact": "gx:ring_wave", "screen": "vignette_heat"},
        "model": {"form": "rifle", "len": 18, "thick": 3, "tall": 3, "scope": True,
                  "fins": True, "metal": "#4f5560"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:glass",
                                   "minecraft:prismarine_shard", "minecraft:diamond"]},
        "twist": "The beam stops at opaque blocks, but through glass, ice or tinted glass it "
                 "refracts into three red/green/blue spectrum beams that fan out and each "
                 "deal damage.",
        "custom": None,
    },
    {
        "id": "helios_sniper",
        "name": "Helios Sniper",
        "description": "Bolt-action 8x green needle; hold breath, kill-cam slow on far kills.",
        "family": "laser", "tier": "epic", "archetype": "charge", "dps": 22,
        "scope": "scope8", "zoom": 8.0,
        "dot": {"style": "dot", "color": "#5aff6a", "range": 150},
        "ammo": {"type": "cell", "mag": 5}, "heat": None, "hud": {"kind": "charge"},
        "palette": {"name": "laser_helios", "core": "#f0fff0", "glow": "#5aff6a",
                    "trail": "#1a7a2a", "accent": "#b8ffc0"},
        "shape": {"projectile": "needle", "muzzle": "ring"},
        "sound": [["crossbow.shoot", 0.9, 1.1, 0], ["beacon.activate", 0.4, 0.9, 3]],
        "params": {"mode": "hitscan", "hold_ticks": 24, "min_ticks": 6, "rate": 34,
                   "range": 150, "pierce": 3, "width": 0.12, "heat_rate": 0.3,
                   "breath_ticks": 20,
                   "tiers": [{"ticks": 6, "damage": 12, "pierce": 1, "range": 80, "size": 0.5},
                             {"ticks": 24, "damage": 30, "pierce": 3, "range": 150, "size": 1.0}]},
        "hooks": {"on_hit": [{"vfx": "gx:star_flash", "size": 0.6, "life": 0.2}], "on_tick": []},
        "vfx": {"idle": "gx:ember_trail", "charge": "gx:swirl", "muzzle": "gx:ring_wave",
                "body": "gx:beam_needle", "impact": "gx:star_flash", "screen": "vignette_heat"},
        "model": {"form": "sniper", "len": 40, "metal": "#3f5a42"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:diamond", "minecraft:glass"]},
        "twist": "Sneak-hold one second steadies the reticle (hold breath); a kill shot "
                 "beyond 60 blocks is a kill-cam beat that slows nearby mobs for 2 s.",
        "custom": "helios_sniper",
    },
    {
        "id": "mirror_pistol",
        "name": "Ricochet Laser Pistol",
        "description": "Rapid orange sidearm; beams ricochet off polished blocks.",
        "family": "laser", "tier": "common", "archetype": "hitscan", "dps": 8,
        "scope": "iron", "zoom": 1.0,
        "dot": {"style": "dot", "color": "#ff8a2a", "range": 30},
        "ammo": {"type": "cell", "mag": 12}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "laser_mirror", "core": "#fff2e0", "glow": "#ff8a2a",
                    "trail": "#a04a10", "accent": "#ffc07a"},
        "shape": {"projectile": "hex", "muzzle": "plate"},
        "sound": [["random.bow", 0.5, 1.8, 0], ["note.pling", 0.3, 1.5, 0]],
        "params": {"range": 30, "damage": 4, "rate": 10, "pierce": 0, "ricochet": 3,
                   "ricochet_blocks": ["minecraft:iron_block", "minecraft:gold_block",
                                       "minecraft:quartz_block", "minecraft:glass",
                                       "minecraft:tinted_glass", "minecraft:polished_andesite",
                                       "minecraft:polished_diorite", "minecraft:polished_granite",
                                       "minecraft:polished_blackstone",
                                       "minecraft:polished_deepslate", "minecraft:copper_block",
                                       "minecraft:netherite_block", "minecraft:diamond_block"],
                   "tracer_size": 0.16, "muzzle_size": 0.35},
        "hooks": {"on_hit": [{"vfx": "gx:star_flash", "size": 0.3, "life": 0.15}], "on_tick": []},
        "vfx": {"idle": "gx:ember_trail", "charge": "gx:spark_burst", "muzzle": "gx:star_flash",
                "body": "gx:beam_needle", "impact": "gx:star_flash", "screen": "vignette_heat"},
        "model": {"form": "pistol", "tall": 4, "metal": "#6a5a4a"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:glass", "minecraft:copper_ingot"]},
        "twist": "Beams bounce off polished blocks (iron, gold, quartz, polished stone, "
                 "glass) up to 3 times, drawing the full zig-zag path.",
        "custom": None,
    },
    {
        "id": "gatling_laser",
        "name": "Six-Barrel Gatling Laser",
        "description": "Spin-up auto laser; ramps to a hairline beam, momentum on release.",
        "family": "laser", "tier": "epic", "archetype": "bolt", "dps": 22,
        "scope": "holo", "zoom": 1.5,
        "dot": {"style": "dot_ring", "color": "#ff5a2a", "range": 64},
        "ammo": {"type": "cell", "mag": 60}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "laser_gatling", "core": "#fff0e0", "glow": "#ff5a2a",
                    "trail": "#8a2a08", "accent": "#ffb08a"},
        "shape": {"projectile": "disc", "muzzle": "cluster"},
        "sound": [["random.bow", 0.5, 2.0, 0], ["mob.blaze.burn", 0.3, 1.8, 1]],
        "params": {"speed": 70, "gravity": 0, "lifetime": 30, "rate": 4, "damage": 1,
                   "count": 1, "spread": 2, "size": 0.22, "muzzle_size": 0.3, "auto": True,
                   "spin_ticks": 20, "min_rate": 4, "max_rate": 24, "momentum_ticks": 10},
        "hooks": {"on_hit": [{"status": "slowness", "ticks": 10, "amp": 0}], "on_tick": []},
        "vfx": {"idle": "gx:ember_trail", "charge": "gx:swirl", "muzzle": "gx:muzzle_flash",
                "body": "gx:orb_disc", "impact": "gx:spark_burst", "screen": "vignette_heat"},
        "model": {"form": "disc", "metal": "#5a4a42"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:copper_ingot", "minecraft:redstone"]},
        "twist": "Barrel spin is the gauge: 4 to 24 shots/s over one second, the wielder "
                 "slowed while spun up, and releasing keeps the barrels firing for 0.5 s.",
        "custom": "gatling_laser",
    },
    {
        "id": "tri_beam",
        "name": "Focus Tri-Beam",
        "description": "Three violet beams converge at a dialled focal distance.",
        "family": "laser", "tier": "rare", "archetype": "beam", "dps": 14,
        "scope": "focus", "zoom": 2.0,
        "dot": {"style": "dot_cross", "color": "#c08aff", "range": 48},
        "ammo": {"type": "heat"}, "heat": {"max": 100, "per_shot": 0, "cool": 12},
        "hud": {"kind": "heat"},
        "palette": {"name": "laser_tri", "core": "#ffffff", "glow": "#c08aff",
                    "trail": "#5a3aa8", "accent": "#e0c8ff"},
        "shape": {"projectile": "fork", "muzzle": "tri"},
        "sound": [["beacon.activate", 0.5, 1.6, 0], ["random.fizz", 0.25, 2.0, 0]],
        "params": {"range": 40, "dps": 14, "width": 0.18, "heat_rate": 1.0, "tick_rate": 4,
                   "focal": 16, "focals": [8, 16, 32], "focus_mult": 3.0, "out_mult": 0.3},
        "hooks": {"on_hit": [{"status": "slowness", "ticks": 15, "amp": 0},
                             {"vfx": "gx:star_flash", "size": 0.3, "life": 0.2}],
                  "on_tick": []},
        "vfx": {"idle": "gx:swirl", "charge": "gx:crystal_burst", "muzzle": "gx:crystal_burst",
                "body": "gx:beam_fork", "impact": "gx:ring_wave", "screen": "vignette_heat"},
        "model": {"form": "lance", "len": 24, "rings": 3, "metal": "#4a3f5e"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:amethyst_shard", "minecraft:glass"]},
        "twist": "Three beams converge at a focal distance dialled with sneak-tap "
                 "(8/16/32 blocks); damage is x3 at focus and falls to x0.3 out of focus.",
        "custom": "tri_beam",
    },
    {
        "id": "orbital_designator",
        "name": "Orbital Designator",
        "description": "Lock a spot for 2 s, then a pillar of light slams down.",
        "family": "laser", "tier": "ultimate", "archetype": "lob", "dps": 30,
        "scope": "rangefinder", "zoom": 4.0, "cooldown": 60,
        "dot": {"style": "dot_ring", "color": "#ff3a3a", "range": 120},
        "ammo": {"type": "cell", "mag": 1}, "heat": None, "hud": {"kind": "charge"},
        "palette": {"name": "laser_designator", "core": "#ffffff", "glow": "#ff3a3a",
                    "trail": "#a01010", "accent": "#ff9a9a"},
        "shape": {"projectile": "star", "muzzle": "beacon"},
        "sound": [["beacon.activate", 0.9, 0.8, 0], ["random.explode", 0.9, 0.9, 30]],
        "params": {"speed": 14, "gravity": 0.2, "aoe": 6, "damage": 24, "fuse": 0,
                   "lifetime": 120, "count": 1, "spread": 0, "rate": 40, "size": 0.8,
                   "range": 120, "hold_ticks": 40, "lock_ticks": 40, "strike_delay": 30,
                   "grief": {"radius": 3, "from": ["minecraft:dirt", "minecraft:grass_block",
                             "minecraft:sand", "minecraft:stone", "minecraft:leaves"],
                             "to": "minecraft:air", "cap": 30}},
        "hooks": {"on_hit": [{"vfx": "gx:ring_wave", "size": 2.0, "life": 0.5}], "on_tick": []},
        "vfx": {"idle": "gx:field_glow", "charge": "gx:swirl", "muzzle": "gx:star_flash",
                "body": "gx:beam_bar", "impact": "gx:ring_wave", "screen": "vignette_whiteout"},
        "model": {"form": "pistol", "tall": 4, "metal": "#5a4a4a"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:redstone_block", "minecraft:glowstone_dust"]},
        "twist": "Hold the dot on a spot for 2 s to lock; 1.5 s later a pillar of light "
                 "slams down with a 6-block ground shockwave (60 s cooldown).",
        "custom": "orbital_designator",
    },
    {
        "id": "cutter_beam",
        "name": "Mining Cutter",
        "description": "Short green-white beam that mines blocks, ramping while held.",
        "family": "laser", "tier": "rare", "archetype": "beam", "dps": 14,
        "scope": "iron", "zoom": 1.0,
        "dot": {"style": "dot", "color": "#5aff8a", "range": 8},
        "ammo": {"type": "heat"}, "heat": {"max": 100, "per_shot": 0, "cool": 16},
        "hud": {"kind": "charges"},
        "palette": {"name": "laser_cutter", "core": "#eafff0", "glow": "#5aff8a",
                    "trail": "#1a7a3a", "accent": "#b8ffd0"},
        "shape": {"projectile": "bar", "muzzle": "nozzle"},
        "sound": [["beacon.activate", 0.4, 2.0, 0], ["random.fizz", 0.35, 1.8, 0]],
        "params": {"range": 6, "dps": 14, "width": 0.15, "heat_rate": 0.8, "tick_rate": 4,
                   "ramp_ticks": 60, "charges": 12,
                   "mineable": ["minecraft:stone", "minecraft:cobblestone",
                                "minecraft:deepslate", "minecraft:cobbled_deepslate",
                                "minecraft:granite", "minecraft:diorite", "minecraft:andesite",
                                "minecraft:tuff", "minecraft:dirt", "minecraft:grass_block",
                                "minecraft:sand", "minecraft:sandstone", "minecraft:gravel",
                                "minecraft:netherrack", "minecraft:basalt",
                                "minecraft:blackstone", "minecraft:end_stone",
                                "minecraft:coal_ore", "minecraft:iron_ore",
                                "minecraft:copper_ore", "minecraft:gold_ore",
                                "minecraft:redstone_ore", "minecraft:lapis_ore",
                                "minecraft:diamond_ore", "minecraft:emerald_ore",
                                "minecraft:deepslate_coal_ore", "minecraft:deepslate_iron_ore",
                                "minecraft:deepslate_copper_ore", "minecraft:deepslate_gold_ore",
                                "minecraft:deepslate_redstone_ore", "minecraft:deepslate_lapis_ore",
                                "minecraft:deepslate_diamond_ore",
                                "minecraft:deepslate_emerald_ore",
                                "minecraft:nether_gold_ore", "minecraft:nether_quartz_ore"]},
        "hooks": {"on_hit": [{"status": "slowness", "ticks": 20, "amp": 0}], "on_tick": []},
        "vfx": {"idle": "gx:ember_trail", "charge": "gx:spark_burst", "muzzle": "gx:star_flash",
                "body": "gx:beam_bar", "impact": "gx:spark_burst", "screen": "vignette_heat"},
        "model": {"form": "sprayer", "metal": "#4a5a4a"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:diamond", "minecraft:redstone"]},
        "twist": "Dig speed ramps the longer the beam stays on one block; ore blocks "
                 "sparkle, and the action bar counts the blocks mined (mobGriefing-gated).",
        "custom": "cutter_beam",
    },
]
