"""Family 5: Lightning (white / yellow / electric-blue; forks, arcs, thunder). Weapons 27-32.

Def schema (see docs/weapons/archetypes.md):
  id, name, family, tier, archetype, scope, zoom, dot, dps, ammo, heat, palette, shape,
  sound, params, hooks, vfx{six layers}, model, recipe, twist, hud, cooldown?, description?
"""

WEAPONS = [
    {
        "id": "tesla_coil_gun",
        "name": "Tesla Coil Gun",
        "description": "Forked arc that jumps five targets; the coil charges a sixth jump.",
        "family": "lightning", "tier": "rare", "archetype": "chain", "dps": 14,
        "scope": "holo", "zoom": 1.5,
        "dot": {"style": "dot", "color": "#ffe95a", "range": 40},
        "ammo": {"type": "cell", "mag": 12}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "lightning_tesla", "core": "#ffffff", "glow": "#ffe95a",
                    "trail": "#8a7a10", "accent": "#fff3b0"},
        "shape": {"projectile": "fork", "muzzle": "coil"},
        "sound": [["random.fizz", 0.5, 1.6, 0], ["beacon.activate", 0.5, 1.9, 0]],
        "params": {"range": 20, "jumps": 4, "radius": 6, "falloff": 0.85, "damage": 7,
                   "rate": 8, "auto": False, "muzzle_size": 0.6,
                   "streak_shots": 3, "streak_ticks": 40, "bonus_jumps": 1},
        "hooks": {"on_hit": [{"vfx": "gx:static_arc", "size": 0.6, "life": 0.3, "count": 2}],
                  "on_tick": []},
        "vfx": {"idle": "gx:static_arc", "charge": "gx:swirl", "muzzle": "gx:beam_fork",
                "body": "gx:beam_fork", "impact": "gx:ring_wave", "screen": "vignette_heat"},
        "model": {"form": "rifle", "len": 18, "thick": 3, "tall": 4, "scope": True,
                  "fins": True, "metal": "#6a6250"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:copper_ingot", "minecraft:redstone"]},
        "twist": "The copper coil spins up as you fire: three shots inside 2 s add a sixth "
                 "jump to every arc until the charge lapses.",
        "custom": "tesla_coil_gun",
    },
    {
        "id": "storm_caller",
        "name": "Storm Caller",
        "description": "Mark a spot, then three lightning strikes hunt mobs inside the circle.",
        "family": "lightning", "tier": "epic", "archetype": "lob", "dps": 22,
        "scope": "scope4", "zoom": 4.0,
        "dot": {"style": "dot_ring", "color": "#ffe04a", "range": 80},
        "ammo": {"type": "cell", "mag": 4}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "lightning_storm", "core": "#ffffff", "glow": "#ffe04a",
                    "trail": "#5a4a00", "accent": "#fff0a0"},
        "shape": {"projectile": "star", "muzzle": "cloud"},
        "sound": [["ambient.weather.thunder", 0.7, 1.2, 0], ["random.explode", 0.6, 1.5, 24]],
        "params": {"speed": 40, "gravity": 0, "aoe": 0, "damage": 0, "fuse": 0, "lifetime": 40,
                   "count": 1, "spread": 0, "size": 0.7, "muzzle_size": 0.8, "rate": 40,
                   "cooldown": 6, "range": 80, "strikes": 3, "strike_dmg": 6,
                   "strike_radius": 5, "strike_gap": 10, "telegraph_ticks": 20,
                   "strike_stun": 10, "wet_mult": 1.5},
        "hooks": {"on_hit": [], "on_tick": []},
        "vfx": {"idle": "gx:field_glow", "charge": "gx:swirl", "muzzle": "gx:star_flash",
                "body": "gx:lightning_fork", "impact": "gx:shock_disc", "screen": "arrow_down"},
        "model": {"form": "staff", "len": 26, "metal": "#6a6250"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:copper_ingot",
                                   "minecraft:lightning_rod", "minecraft:glowstone_dust"]},
        "twist": "Strikes auto-target the nearest mob inside the circle instead of the bare "
                 "ground, and mobs standing in water take +50%.",
        "custom": "storm_caller",
    },
    {
        "id": "railgun_mk2",
        "name": "Railgun Mk II",
        "description": "Charge 1.5 s, then a piercing slug that scars the tunnel it crosses.",
        "family": "lightning", "tier": "mythic", "archetype": "charge", "dps": 30,
        "scope": "thermal", "zoom": 8.0,
        "dot": {"style": "dot", "color": "#bfe4ff", "range": 100},
        "ammo": {"type": "cell", "mag": 4}, "heat": {"max": 100, "per_shot": 12, "cool": 6},
        "hud": {"kind": "charge"},
        "palette": {"name": "lightning_rail", "core": "#ffffff", "glow": "#9fd8ff",
                    "trail": "#2a6aa8", "accent": "#d8f0ff"},
        "shape": {"projectile": "needle", "muzzle": "rail"},
        "sound": [["beacon.activate", 0.9, 0.8, 0], ["random.explode", 0.7, 1.6, 2]],
        "params": {"mode": "hitscan", "hold_ticks": 30, "min_ticks": 8, "rate": 40,
                   "range": 100, "pierce": 5, "width": 0.4, "heat_rate": 0.9,
                   "tiers": [{"ticks": 8, "damage": 10, "pierce": 2, "range": 50,
                              "width": 0.25, "size": 0.6},
                             {"ticks": 20, "damage": 22, "pierce": 4, "range": 80,
                              "width": 0.32, "size": 0.8},
                             {"ticks": 30, "damage": 35, "pierce": 5, "range": 100,
                              "width": 0.4, "size": 1.0, "heat": 12}],
                   "knock": 1.4, "knock_radius": 3.5,
                   "grief": {"radius": 2, "from": ["minecraft:stone", "minecraft:deepslate",
                             "minecraft:dirt", "minecraft:gravel", "minecraft:sand",
                             "minecraft:sandstone", "minecraft:cobblestone", "minecraft:tuff",
                             "minecraft:netherrack", "minecraft:andesite", "minecraft:diorite",
                             "minecraft:granite"], "to": "minecraft:glass", "cap": 20}},
        "hooks": {"on_hit": [{"vfx": "gx:shock_disc", "size": 1.6, "life": 0.4}], "on_tick": []},
        "vfx": {"idle": "gx:beam_needle", "charge": "gx:ring_wave", "muzzle": "gx:beam_bar",
                "body": "gx:beam_bar", "impact": "gx:shock_disc", "screen": "thermal_tint"},
        "model": {"form": "lance", "len": 34, "rings": 4, "metal": "#55606d"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:diamond", "minecraft:copper_block"]},
        "twist": "The slug pierces five mobs and cuts a glowing glass tunnel through soft "
                 "rock, while its shockwave ring knocks everything near the path away.",
        "custom": "railgun_mk2",
    },
    {
        "id": "volt_whip",
        "name": "Volt Whip",
        "description": "Crack a mob to stun and reel it in; alt-use grapples to a block.",
        "family": "lightning", "tier": "rare", "archetype": "tether", "dps": 14,
        "scope": "iron", "zoom": 1.0,
        "dot": {"style": "dot", "color": "#ffd23a", "range": 10},
        "ammo": {"type": "cell", "mag": 10}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "lightning_volt", "core": "#ffffff", "glow": "#ffd23a",
                    "trail": "#7a5a00", "accent": "#ffe89a"},
        "shape": {"projectile": "fork", "muzzle": "hilt"},
        "sound": [["random.fizz", 0.6, 1.4, 0], ["mob.blaze.burn", 0.3, 1.8, 0]],
        "params": {"range": 10, "damage": 8, "rate": 8, "pull": 1.4, "stun": 1,
                   "grapple_cooldown": 3, "muzzle_size": 0.4},
        "hooks": {"on_hit": [{"status": "slowness", "ticks": 20, "amp": 4},
                             {"vfx": "gx:ring_wave", "size": 1.0, "life": 0.4}],
                  "on_tick": []},
        "vfx": {"idle": "gx:static_arc", "charge": "gx:spark_burst", "muzzle": "gx:lightning_fork",
                "body": "gx:beam_fork", "impact": "gx:ring_wave", "screen": "marker_hit"},
        "model": {"form": "gauntlet", "metal": "#6a6250"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:copper_ingot",
                                   "minecraft:string", "minecraft:redstone"]},
        "twist": "The whip crackles in an S-curve and wraps the reeled mob in rings of arcs; "
                 "sneak-use anchors it to a block and pulls you across the gap.",
        "custom": None,
    },
    {
        "id": "thunder_shotgun",
        "name": "Thunder Shotgun",
        "description": "Pump-action fan of six arcs; the muzzle clap shoves mobs back.",
        "family": "lightning", "tier": "common", "archetype": "cone", "dps": 8,
        "scope": "iron", "zoom": 1.0,
        "dot": {"style": "dot", "color": "#ffcf2b", "range": 10},
        "ammo": {"type": "cell", "mag": 6}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "lightning_thunder", "core": "#fffbe0", "glow": "#ffcf2b",
                    "trail": "#6a5a00", "accent": "#fff0a8"},
        "shape": {"projectile": "plume", "muzzle": "pump"},
        "sound": [["random.explode", 0.7, 1.4, 0], ["ambient.weather.thunder", 0.6, 1.5, 1]],
        "params": {"range": 10, "angle": 55, "dps": 8, "burst": True, "rate": 25,
                   "knockback": 0, "arcs": 6, "particle_size": 0.55, "muzzle_size": 0.7},
        "hooks": {"on_hit": [{"status": "slowness", "ticks": 10, "amp": 4},
                             {"knockback": 1.2, "dir": "away"},
                             {"vfx": "gx:static_arc", "size": 0.7, "life": 0.3, "count": 3}],
                  "on_tick": []},
        "vfx": {"idle": "gx:spark_burst", "charge": "gx:swirl", "muzzle": "gx:lightning_fork",
                "body": "gx:orb_plume", "impact": "gx:ring_wave", "screen": "marker_kill"},
        "model": {"form": "rifle", "len": 14, "thick": 4, "tall": 3, "underbarrel": True,
                  "metal": "#6a6250"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:gunpowder", "minecraft:copper_ingot"]},
        "twist": "Each blast shoves its target 1.2 back and cracks a static arc, so a "
                 "point-blank pump clears the space around you.",
        "custom": None,
    },
    {
        "id": "glaive_disc",
        "name": "Arc Glaive Thrower",
        "description": "Spinning lightning disc that bounces four targets then boomerangs home.",
        "family": "lightning", "tier": "epic", "archetype": "bolt", "dps": 22,
        "scope": "dot", "zoom": 2.0,
        "dot": {"style": "dot", "color": "#6ab8ff", "range": 48},
        "ammo": {"type": "cell", "mag": 5}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "lightning_glaive", "core": "#ffffff", "glow": "#6ab8ff",
                    "trail": "#1f4f8a", "accent": "#bfe4ff"},
        "shape": {"projectile": "disc", "muzzle": "rotor"},
        "sound": [["crossbow.shoot", 0.7, 1.4, 0], ["random.fizz", 0.3, 1.9, 1]],
        "params": {"speed": 45, "gravity": 0, "lifetime": 80, "rate": 20, "damage": 11,
                   "count": 1, "spread": 0, "size": 0.5, "muzzle_size": 0.6,
                   "pierce": 3, "bounce": 0, "boomerang": 25, "catch_radius": 2,
                   "split": 3, "split_spread": 26, "split_life": 30, "max_splits": 1},
        "hooks": {"on_hit": [{"vfx": "gx:spark_burst", "size": 0.5, "life": 0.4, "count": 4}],
                  "on_tick": []},
        "vfx": {"idle": "gx:swirl", "charge": "gx:spark_burst", "muzzle": "gx:orb_disc",
                "body": "gx:orb_disc", "impact": "gx:debris_burst", "screen": "star"},
        "model": {"form": "disc", "metal": "#55606d"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:copper_ingot", "minecraft:amethyst_shard"]},
        "twist": "The disc bounces through four targets, then reverses and boomerangs home "
                 "after 25 blocks; re-pressing mid-air splits it into three.",
        "custom": "glaive_disc",
    },
]
