"""Family 1: Plasma (blue / cyan / magenta, soft orbs, ring shockwaves). Weapons 01-08.

Def schema (see docs/weapons/archetypes.md):
  id, name, family, tier, archetype, scope, zoom, dot, dps, ammo, heat, palette, shape,
  sound, params, hooks, vfx{six layers}, model, recipe, twist, hud, cooldown?, description?
"""

CELL = {"type": "cell", "mag": 24}
HEAT = {"type": "heat"}

WEAPONS = [
    {
        "id": "pulse_carbine",
        "name": "Pulse Carbine",
        "description": "3-round cyan burst. Third bolt is a kicker.",
        "family": "plasma", "tier": "common", "archetype": "bolt", "dps": 8,
        "scope": "dot", "zoom": 2.0,
        "dot": {"style": "dot", "color": "#22e0ff", "range": 64},
        "ammo": {"type": "cell", "mag": 24}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "plasma_cyan", "core": "#eaffff", "glow": "#22e0ff",
                    "trail": "#0a6fa8", "accent": "#7fe6ff"},
        "shape": {"projectile": "teardrop", "muzzle": "hex"},
        "sound": [["random.bow", 0.7, 1.7, 0], ["beacon.activate", 0.4, 1.4, 0]],
        "params": {"speed": 60, "gravity": 0, "lifetime": 50, "rate": 4, "damage": 4,
                   "count": 1, "spread": 0, "size": 0.35, "muzzle_size": 0.45,
                   "burst": 3, "burst_gap": 3, "kicker_mult": 1.5},
        "hooks": {"on_hit": [{"vfx": "gx:ring_wave", "size": 0.9, "life": 0.3}], "on_tick": []},
        "vfx": {"idle": "gx:orb_soft_orb", "charge": "gx:orb_soft_orb", "muzzle": "gx:orb_hex",
                "body": "gx:orb_teardrop", "impact": "gx:ring_wave", "screen": "vignette_heat"},
        "model": {"form": "rifle", "len": 18, "thick": 3, "tall": 3, "scope": True,
                  "metal": "#4d5866"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:copper_ingot", "minecraft:redstone"]},
        "twist": "Third bolt of every burst is a larger kicker (+50% damage, ring impact).",
        "custom": "pulse_carbine",
    },
    {
        "id": "plasma_repeater",
        "name": "Plasma Repeater",
        "description": "Full-auto violet bolts with a perfect-vent window.",
        "family": "plasma", "tier": "rare", "archetype": "bolt", "dps": 14,
        "scope": "holo", "zoom": 1.5,
        "dot": {"style": "dot_ring", "color": "#b06aff", "range": 64},
        "ammo": {"type": "heat"}, "heat": {"max": 100, "per_shot": 5, "cool": 14, "vent": True},
        "hud": {"kind": "heat"},
        "palette": {"name": "plasma_violet", "core": "#f0e6ff", "glow": "#b06aff",
                    "trail": "#5a2a9a", "accent": "#d8aaff"},
        "shape": {"projectile": "dart", "muzzle": "star"},
        "sound": [["random.bow", 0.6, 1.9, 0], ["random.fizz", 0.3, 1.6, 2]],
        "params": {"speed": 55, "gravity": 0, "lifetime": 50, "rate": 2, "damage": 3,
                   "count": 1, "size": 0.3, "muzzle_size": 0.4, "auto": True,
                   "heat_rate": 5, "vent_bonus_ticks": 60, "vent_mult": 1.35},
        "hooks": {"on_hit": [{"status": "slowness", "ticks": 20, "amp": 0}], "on_tick": []},
        "vfx": {"idle": "gx:ember_trail", "charge": "gx:spark_burst", "muzzle": "gx:star_flash",
                "body": "gx:orb_dart", "impact": "gx:spark_burst", "screen": "vignette_heat"},
        "model": {"form": "rifle", "len": 16, "thick": 4, "tall": 3, "fins": True,
                  "metal": "#4a4f66"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:amethyst_shard", "minecraft:blaze_powder"]},
        "twist": "Perfect vent: at overheat a 2s sliding marker appears; releasing in the "
                 "green zone clears heat instantly and grants a 3s damage boost.",
        "custom": "plasma_repeater",
    },
    {
        "id": "plasma_scattergun",
        "name": "Sticky Scattergun",
        "description": "8 sticky magenta globs that chain-detonate.",
        "family": "plasma", "tier": "rare", "archetype": "bolt", "dps": 14,
        "scope": "iron", "zoom": 1.0,
        "dot": {"style": "dot", "color": "#ff5ad8", "range": 40},
        "ammo": {"type": "cell", "mag": 8}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "plasma_magenta", "core": "#ffe6fa", "glow": "#ff5ad8",
                    "trail": "#a0246e", "accent": "#ffb0ee"},
        "shape": {"projectile": "glob", "muzzle": "flared"},
        "sound": [["random.bow", 0.8, 1.2, 0], ["mob.blaze.burn", 0.5, 1.4, 1]],
        "params": {"speed": 25, "gravity": 0.02, "lifetime": 60, "rate": 18, "damage": 3,
                   "count": 8, "spread": 12, "size": 0.4, "muzzle_size": 0.6, "stick": True,
                   "fuse": 30, "aoe": 2.0, "aoe_mult": 1.6, "chain_radius": 3,
                   "alt_spread": 5},
        "hooks": {"on_hit": [{"vfx": "gx:star_flash", "size": 0.7, "life": 0.25}], "on_tick": []},
        "vfx": {"idle": "gx:orb_glob", "charge": "gx:orb_glob", "muzzle": "gx:orb_glob",
                "body": "gx:orb_glob", "impact": "gx:star_flash", "screen": "vignette_heat"},
        "model": {"form": "launcher", "len": 12, "metal": "#5a4a5e"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:magenta_dye", "minecraft:slime_ball"]},
        "twist": "Globs stick to the first block or mob they touch and detonate 1.5s later, "
                 "chain-detonating other stuck globs within 3 blocks.",
        "custom": "plasma_scattergun",
    },
    {
        "id": "splitter_rifle",
        "name": "Splitter Rifle",
        "description": "Splits into homing shards at range or on impact.",
        "family": "plasma", "tier": "epic", "archetype": "bolt", "dps": 22,
        "scope": "dot", "zoom": 2.0,
        "dot": {"style": "dot", "color": "#3aff9a", "range": 64},
        "ammo": {"type": "cell", "mag": 12}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "plasma_teal", "core": "#eafff4", "glow": "#3aff9a",
                    "trail": "#0e7a52", "accent": "#9affc8"},
        "shape": {"projectile": "needle", "muzzle": "prism"},
        "sound": [["crossbow.shoot", 0.8, 1.3, 0], ["beacon.activate", 0.4, 1.8, 1]],
        "params": {"speed": 45, "gravity": 0, "lifetime": 40, "rate": 12, "damage": 9,
                   "count": 1, "size": 0.32, "muzzle_size": 0.5, "split": 3, "split_at": 12,
                   "split_homing": 8, "split_speed": 40, "split_life": 40, "max_splits": 2,
                   "pierce": 2},
        "hooks": {"on_hit": [{"vfx": "gx:debris_burst", "size": 0.4, "life": 0.4, "count": 4}],
                  "on_tick": []},
        "vfx": {"idle": "gx:swirl", "charge": "gx:swirl", "muzzle": "gx:crystal_burst",
                "body": "gx:orb_needle", "impact": "gx:debris_burst", "screen": "vignette_toxic"},
        "model": {"form": "rifle", "len": 20, "thick": 3, "tall": 3, "scope": True,
                  "fins": True, "metal": "#3f5f56"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:emerald", "minecraft:amethyst_shard"]},
        "twist": "Shards inherit the parent's remaining pierce and can re-split once on a "
                 "wall bounce.",
        "custom": "splitter_rifle",
    },
    {
        "id": "plasma_lance",
        "name": "Plasma Lance",
        "description": "Charge 1.2s, then a piercing beam with travelling rings.",
        "family": "plasma", "tier": "epic", "archetype": "charge", "dps": 22,
        "scope": "scope4", "zoom": 4.0,
        "dot": {"style": "dot_ring", "color": "#22e0ff", "range": 80},
        "ammo": {"type": "cell", "mag": 6}, "heat": None, "hud": {"kind": "charge"},
        "palette": {"name": "plasma_cyan_lance", "core": "#ffffff", "glow": "#22e0ff",
                    "trail": "#0b5f96", "accent": "#a8f0ff"},
        "shape": {"projectile": "orb", "muzzle": "ring"},
        "sound": [["beacon.activate", 0.8, 0.8, 0], ["random.explode", 0.5, 1.6, 2]],
        "params": {"mode": "hitscan", "hold_ticks": 24, "min_ticks": 6, "rate": 30,
                   "range": 60, "pierce": 5, "width": 0.35, "heat_rate": 0.5,
                   "tiers": [{"ticks": 6, "damage": 8, "pierce": 2, "range": 40, "size": 0.6},
                             {"ticks": 24, "damage": 22, "pierce": 5, "range": 60, "size": 1.0}],
                   "rings": 3},
        "hooks": {"on_hit": [{"status": "slowness", "ticks": 20, "amp": 0}], "on_tick": []},
        "vfx": {"idle": "gx:orb_soft_orb", "charge": "gx:swirl", "muzzle": "gx:ring_wave",
                "body": "gx:beam_bar", "impact": "gx:shock_disc", "screen": "vignette_heat"},
        "model": {"form": "lance", "len": 30, "rings": 3, "metal": "#41566b"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:diamond", "minecraft:lapis_lazuli"]},
        "twist": "Three energy rings travel down the beam and each applies a separate "
                 "shockwave hit at the first mob it reaches.",
        "custom": "plasma_lance",
    },
    {
        "id": "sunfire_cannon",
        "name": "Sunfire Cannon",
        "description": "Slow golden plasma sphere leaving a burning sun-scar.",
        "family": "plasma", "tier": "mythic", "archetype": "bolt", "dps": 30,
        "scope": "scope4", "zoom": 4.0,
        "dot": {"style": "dot_ring", "color": "#ffb02b", "range": 80},
        "ammo": {"type": "cell", "mag": 4}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "plasma_solar", "core": "#fff6d0", "glow": "#ffb02b",
                    "trail": "#a85a10", "accent": "#ffd98a"},
        "shape": {"projectile": "soft_orb", "muzzle": "cage"},
        "sound": [["mob.ghast.shoot", 0.8, 0.7, 0], ["random.explode", 0.9, 0.9, 2]],
        "params": {"speed": 8, "gravity": 0.03, "lifetime": 80, "rate": 40, "damage": 14,
                   "count": 1, "size": 1.2, "muzzle_size": 1.0, "aoe": 5.0, "aoe_mult": 1.0,
                   "charge_ticks": 50, "grief": {"radius": 3, "from": ["minecraft:sand",
                   "minecraft:snow_block", "minecraft:ice"], "to": "minecraft:glass", "cap": 20}},
        "hooks": {"on_hit": [{"field": "sun_scar", "radius": 3, "life": 120, "dps": 4,
                              "extra": {"status": [{"id": "weakness", "ticks": 40, "amp": 0}]}}],
                  "on_tick": []},
        "vfx": {"idle": "gx:ember_trail", "charge": "gx:ember_trail", "muzzle": "gx:orb_star",
                "body": "gx:orb_soft_orb", "impact": "gx:ring_wave", "screen": "vignette_heat"},
        "model": {"form": "cannon", "len": 14, "metal": "#6b5a3a"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:gold_ingot",
                                   "minecraft:blaze_rod", "minecraft:netherrack"]},
        "twist": "Leaves a sun-scar pool for 6s that burns anything inside and melts "
                 "sand/snow/ice within 3 blocks (gated by mobGriefing, cap 20 blocks).",
        "custom": "sunfire_cannon",
    },
    {
        "id": "ion_disruptor",
        "name": "Ion Disruptor",
        "description": "Blue-static pulse; stuns machines and debuffs mobs.",
        "family": "plasma", "tier": "rare", "archetype": "hitscan", "dps": 14,
        "scope": "holo", "zoom": 1.5,
        "dot": {"style": "dot_cross", "color": "#5ab4ff", "range": 64},
        "ammo": {"type": "cell", "mag": 18}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "plasma_ion", "core": "#eaf6ff", "glow": "#5ab4ff",
                    "trail": "#1a4a8a", "accent": "#a0d8ff"},
        "shape": {"projectile": "spark", "muzzle": "coil"},
        "sound": [["random.fizz", 0.6, 1.9, 0], ["beacon.activate", 0.4, 2.0, 0]],
        "params": {"range": 40, "damage": 5, "rate": 10, "pierce": 1, "tracer_size": 0.25,
                   "muzzle_size": 0.5,
                   "bonus_vs": {"family": "gx_droid", "mult": 1.4}},
        "hooks": {"on_hit": [{"status": "slowness", "ticks": 80, "amp": 3},
                             {"status": "weakness", "ticks": 80, "amp": 0},
                             {"stun": 60},
                             {"vfx": "gx:static_arc", "size": 0.8, "life": 0.3}],
                  "on_tick": []},
        "vfx": {"idle": "gx:static_arc", "charge": "gx:static_arc", "muzzle": "gx:static_arc",
                "body": "gx:beam_fork", "impact": "gx:static_arc", "screen": "vignette_heat"},
        "model": {"form": "pistol", "tall": 3, "metal": "#3f4a63"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:copper_ingot",
                                   "minecraft:redstone", "minecraft:glass"]},
        "twist": "Stunned machines emit a spark halo and take +40% damage from all sources.",
        "custom": None,
    },
    {
        "id": "twin_photon_smg",
        "name": "Twin Photon SMG",
        "description": "Two barrels alternate; every 12th shot is a golden tracer.",
        "family": "plasma", "tier": "common", "archetype": "bolt", "dps": 8,
        "scope": "holo", "zoom": 1.5,
        "dot": {"style": "dot", "color": "#ffe95a", "range": 48},
        "ammo": {"type": "cell", "mag": 36}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "plasma_photon", "core": "#fffde6", "glow": "#ffe95a",
                    "trail": "#a8841a", "accent": "#fff0a0"},
        "shape": {"projectile": "disc", "muzzle": "twin"},
        "sound": [["random.bow", 0.5, 2.2, 0], ["note.pling", 0.3, 2.0, 0]],
        "params": {"speed": 50, "gravity": 0, "lifetime": 30, "rate": 2, "damage": 2,
                   "count": 1, "size": 0.22, "muzzle_size": 0.3, "auto": True,
                   "twin_barrels": True, "tracer_every": 12},
        "hooks": {"on_hit": [{"vfx": "gx:spark_burst", "size": 0.3, "life": 0.3, "count": 3}],
                  "on_tick": []},
        "vfx": {"idle": "gx:orb_star", "charge": "gx:orb_star", "muzzle": "gx:orb_disc",
                "body": "gx:orb_disc", "impact": "gx:spark_burst", "screen": "vignette_heat"},
        "model": {"form": "smg", "len": 10, "twin": True, "metal": "#5c5a3a"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:gold_ingot", "minecraft:glowstone_dust"]},
        "twist": "Alternating barrels: muzzle flashes alternate sides, and every 12th shot "
                 "is a golden tracer that pings a hit marker with a coin sound.",
        "custom": "twin_photon_smg",
    },
]
