"""Family 6: Void & Gravity (purple / black / indigo, distortion and inversions).
Weapons 33-38.

Def schema (see docs/weapons/archetypes.md):
  id, name, family, tier, archetype, scope, zoom, dot, dps, ammo, heat, palette, shape,
  sound, params, hooks, vfx{six layers}, model, recipe, twist, hud, cooldown?, description?
"""

WEAPONS = [
    {
        "id": "gravity_well_launcher",
        "name": "Gravity Well Launcher",
        "description": "Orb that opens a 4 s singularity; your own bolts bend into it.",
        "family": "void", "tier": "epic", "archetype": "lob", "dps": 22,
        "scope": "rangefinder", "zoom": 4.0,
        "dot": {"style": "dot_ring", "color": "#9a5aff", "range": 96},
        "ammo": {"type": "cell", "mag": 3}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "void_singularity", "core": "#f0e0ff", "glow": "#7a2ae0",
                    "trail": "#2a0a4a", "accent": "#b08aff"},
        "shape": {"projectile": "soft_orb", "muzzle": "orb_cage"},
        "sound": [["mob.ghast.shoot", 0.7, 0.6, 0], ["beacon.activate", 0.4, 0.8, 2]],
        "params": {"speed": 14, "gravity": 0.2, "aoe": 4.5, "damage": 12, "fuse": 0,
                   "lifetime": 100, "count": 1, "spread": 0, "rate": 30, "size": 0.9,
                   "muzzle_size": 0.8, "range": 30, "bend": 0.35, "bend_range": 18},
        "hooks": {"on_hit": [{"field": "singularity", "radius": 6, "life": 80, "pull": 0.6,
                              "dps": 5, "extra": {"collapse": {"dmg": 10, "knock": 1.6}}}],
                  "on_tick": []},
        "vfx": {"idle": "gx:field_glow", "charge": "gx:swirl", "muzzle": "gx:orb_soft_orb",
                "body": "gx:orb_soft_orb", "impact": "gx:shock_disc", "screen": "vignette_void"},
        "model": {"form": "launcher", "len": 16, "metal": "#241a33"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:obsidian",
                                   "minecraft:ender_pearl", "minecraft:iron_ingot"]},
        "twist": "The singularity drags mobs into orbit, grounds flying mobs and bends your "
                 "own in-flight bolts into the well; when it collapses it bursts outward.",
        "custom": "gravity_well_launcher",
    },
    {
        "id": "void_beam",
        "name": "Void Beam Rifle",
        "description": "Channeled void beam; four hits open a rift that yanks the target up.",
        "family": "void", "tier": "epic", "archetype": "beam", "dps": 22,
        "scope": "holo", "zoom": 1.5,
        "dot": {"style": "dot", "color": "#100a1e", "range": 25},
        "ammo": {"type": "heat"}, "heat": {"max": 100, "per_shot": 0, "cool": 9},
        "hud": {"kind": "heat"},
        "palette": {"name": "void_rift", "core": "#e8d8ff", "glow": "#6a1ad0",
                    "trail": "#14021f", "accent": "#a070ff"},
        "shape": {"projectile": "bar", "muzzle": "slit"},
        "sound": [["beacon.activate", 0.6, 0.7, 0], ["random.fizz", 0.4, 0.8, 0]],
        "params": {"range": 25, "dps": 16, "width": 0.3, "heat_rate": 1.1, "tick_rate": 4,
                   "marks": 4, "rift_damage": 20},
        "hooks": {"on_hit": [{"status": "slowness", "ticks": 20, "amp": 0}], "on_tick": []},
        "vfx": {"idle": "gx:field_glow", "charge": "gx:swirl", "muzzle": "gx:beam_needle",
                "body": "gx:beam_bar", "impact": "gx:ring_wave", "screen": "vignette_void"},
        "model": {"form": "rifle", "len": 22, "thick": 3, "tall": 3, "scope": True,
                  "metal": "#100c18"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:obsidian",
                                   "minecraft:amethyst_shard", "minecraft:echo_shard"]},
        "twist": "Hits stack Void Marks on a target; the fourth mark tears a rift that pulls "
                 "it upward and releases it with heavy damage.",
        "custom": "void_beam",
    },
    {
        "id": "blink_rifle",
        "name": "Blink Rifle",
        "description": "Violet orb; impact teleports you there, alt-fire swaps with the mob.",
        "family": "void", "tier": "rare", "archetype": "bolt", "dps": 14,
        "scope": "dot", "zoom": 2.0, "cooldown": 5,
        "dot": {"style": "dot", "color": "#9a5aff", "range": 48},
        "ammo": {"type": "cell", "mag": 6}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "void_blink", "core": "#f6ecff", "glow": "#9a5aff",
                    "trail": "#3a1a7a", "accent": "#c8a8ff"},
        "shape": {"projectile": "soft_orb", "muzzle": "ring_gate"},
        "sound": [["random.orb", 0.6, 1.6, 0], ["beacon.activate", 0.4, 2.0, 1]],
        "params": {"speed": 55, "gravity": 0, "homing": 0, "homing_turn": 0.25,
                   "lifetime": 16, "rate": 15, "damage": 7, "count": 1, "spread": 0,
                   "size": 0.4, "muzzle_size": 0.5, "aoe": 2.5, "aoe_mult": 0.6,
                   "range": 40, "teleport": "hit", "swap_on_aim": True, "search": 2},
        "hooks": {"on_hit": [{"vfx": "gx:star_flash", "size": 0.5, "life": 0.2}], "on_tick": []},
        "vfx": {"idle": "gx:swirl", "charge": "gx:crystal_burst", "muzzle": "gx:star_flash",
                "body": "gx:orb_soft_orb", "impact": "gx:star_flash", "screen": "vignette_void"},
        "model": {"form": "rifle", "len": 16, "thick": 3, "tall": 3, "scope": True,
                  "fins": True, "metal": "#2a2340"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:ender_pearl",
                                   "minecraft:iron_ingot", "minecraft:amethyst_shard"]},
        "twist": "Impact teleports you to the landing point (safe-spot search, 5 s cooldown); "
                 "aiming swaps you with the mob you hit.",
        "custom": "blink_rifle",
    },
    {
        "id": "umbra_smg",
        "name": "Umbra SMG",
        "description": "Silent dark bolts; five hits detonate a shadow burst.",
        "family": "void", "tier": "rare", "archetype": "bolt", "dps": 14,
        "scope": "holo", "zoom": 1.5,
        "dot": {"style": "dot", "color": "#4a2a7a", "range": 40},
        "ammo": {"type": "cell", "mag": 30}, "heat": None, "hud": {"kind": "ammo"},
        "palette": {"name": "void_umbra", "core": "#d8c8f0", "glow": "#3a1a6a",
                    "trail": "#0a0512", "accent": "#7a5aa8"},
        "shape": {"projectile": "dart", "muzzle": "suppressor"},
        "sound": [["random.fizz", 0.15, 1.9, 0]],
        "params": {"speed": 50, "gravity": 0, "homing": 0, "lifetime": 30, "rate": 2,
                   "damage": 3, "count": 1, "spread": 0, "size": 0.24, "muzzle_size": 0.25,
                   "auto": True, "marks": 5, "mark_aoe": 3, "mark_damage": 12},
        "hooks": {"on_hit": [{"status": "weakness", "ticks": 20, "amp": 0}], "on_tick": []},
        "vfx": {"idle": "gx:smoke_trail", "charge": "gx:smoke_trail", "muzzle": "gx:orb_dart",
                "body": "gx:orb_dart", "impact": "gx:debris_burst", "screen": "vignette_void"},
        "model": {"form": "smg", "len": 10, "twin": False, "metal": "#17131f"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:black_dye", "minecraft:echo_shard"]},
        "twist": "Silent dark bolts leave Shadow Marks; the fifth mark on one mob detonates "
                 "it in a 3-block shadow burst.",
        "custom": "umbra_smg",
    },
    {
        "id": "black_hole_cannon",
        "name": "Black Hole Cannon",
        "description": "5 s charge, then a slow hole that swallows projectiles and collapses.",
        "family": "void", "tier": "ultimate", "archetype": "bolt", "dps": 30,
        "scope": "scope4", "zoom": 4.0, "cooldown": 60,
        "dot": {"style": "dot_ring", "color": "#b06aff", "range": 96},
        "ammo": {"type": "cell", "mag": 1}, "heat": None, "hud": {"kind": "charge"},
        "palette": {"name": "void_collapse", "core": "#ffffff", "glow": "#5a1ac0",
                    "trail": "#0a0316", "accent": "#9a70ff"},
        "shape": {"projectile": "soft_orb", "muzzle": "maw"},
        "sound": [["mob.ghast.shoot", 0.8, 0.5, 0], ["random.explode", 0.9, 0.7, 2]],
        "params": {"speed": 4, "gravity": 0, "lifetime": 200, "rate": 40, "damage": 20,
                   "count": 1, "size": 1.4, "muzzle_size": 1.2, "aoe": 5.0, "aoe_mult": 1.0,
                   "charge_ticks": 100, "hold_ticks": 100, "swallow_radius": 3},
        "hooks": {"on_hit": [{"field": "black_hole", "radius": 5, "life": 80, "pull": 0.8,
                              "dps": 6, "extra": {"collapse": {"dmg": 14, "knock": 1.8}}}],
                  "on_tick": []},
        "vfx": {"idle": "gx:field_glow", "charge": "gx:swirl", "muzzle": "gx:orb_soft_orb",
                "body": "gx:orb_soft_orb", "impact": "gx:star_flash",
                "screen": "vignette_whiteout"},
        "model": {"form": "cannon", "len": 16, "metal": "#1b1428"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:obsidian",
                                   "minecraft:nether_star", "minecraft:ender_pearl"]},
        "twist": "The slow hole swallows other projectiles and pulls loose items in; when it "
                 "collapses it flashes white and rings outward (60 s cooldown).",
        "custom": "black_hole_cannon",
    },
    {
        "id": "repulsor_gauntlet",
        "name": "Repulsor Gauntlet",
        "description": "Palm shockwave; hold to charge, fire at the ground to rocket-jump.",
        "family": "void", "tier": "rare", "archetype": "cone", "dps": 14,
        "scope": "holo", "zoom": 1.5,
        "dot": {"style": "dot_ring", "color": "#8a5aff", "range": 12},
        "ammo": {"type": "heat"}, "heat": {"max": 100, "per_shot": 0, "cool": 12},
        "hud": {"kind": "charge"},
        "palette": {"name": "void_repulsor", "core": "#f4ecff", "glow": "#8a5aff",
                    "trail": "#3a1a6a", "accent": "#c0a0ff"},
        "shape": {"projectile": "disc", "muzzle": "palm"},
        "sound": [["mob.irongolem.throw", 0.5, 1.3, 0], ["random.fizz", 0.3, 1.7, 2]],
        "params": {"range": 8, "angle": 55, "dps": 6, "knockback": 2.6, "rate": 20,
                   "charge": True, "hold_ticks": 20, "charge_mult": 1.2, "heat_rate": 2,
                   "particle_size": 0.6, "muzzle_size": 0.8, "cause": "explosion",
                   "jump_power": 0.8},
        "hooks": {"on_hit": [{"vfx": "gx:ring_wave", "size": 1.2, "life": 0.3}], "on_tick": []},
        "vfx": {"idle": "gx:field_glow", "charge": "gx:swirl", "muzzle": "gx:shock_disc",
                "body": "gx:orb_disc", "impact": "gx:ring_wave", "screen": "vignette_void"},
        "model": {"form": "gauntlet", "metal": "#2c2438"},
        "recipe": {"ingredients": ["gx:energy_cell", "minecraft:iron_ingot",
                                   "minecraft:amethyst_shard", "minecraft:gunpowder"]},
        "twist": "Hold to charge a wider, harder blast; firing at the ground while airborne "
                 "launches you upward on a repulsor burst.",
        "custom": "repulsor_gauntlet",
    },
]
